#!/bin/sh

if [ $# -ne 1 ]; then
    echo "usage: clone <name>"
    exit 1
fi

USER="compromyse"

base_dir="$HOME"
new_repo="${base_dir}/$1"

case $new_repo in
    *\.git)
	;;
    *)
	new_repo="${new_repo}.git"
	;;
esac

if [ -d "$new_repo" ]; then
    echo "$new_repo already exists"
    exit 1
fi

mkdir "$new_repo"
git clone --bare "git@github.com:$USER/$1" "$new_repo" \
    && echo "Cloned Git repository to: git@$(uname -n):$1"
