#!/bin/sh

if [ $# -ne 1 ]; then
    echo "usage: desc <name>"
    exit 1
fi

base_dir="$HOME"
repo="${base_dir}/$1"

case $repo in
    *\.git)
	;;
    *)
	repo="${repo}.git"
	;;
esac

if [ ! -d "$repo" ]; then
    echo "$repo doesn't exist"
    exit 1
fi

vi "${repo}/description"
