#!/usr/bin/env bash

echo """Welcome to git-shell on $(uname -n)!

Available Commands:
ls
init <name>
desc <name>
rm <name>
ignore <name>
unignore <name>
bash
clone-all-github
setup-receive-hooks
setup-receive-hook <name>
setup-remote <name> <remote_name> <remote>
"""
