#!/usr/bin/env bash

echo """Welcome to git-shell on $(uname -n)!

Available Commands:
ls
init <name>
desc <name>
rm <name>
ignore <name>
unignore <name>
bash
clone-all-github
setup-receive-hooks
"""
