#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "usage: init <name>"
    exit 1
fi

base_dir="$HOME"
new_repo="${base_dir}/$1"

case $new_repo in
    *\.git)
	;;
    *)
	new_repo="${new_repo}.git"
	;;
esac

if [ -d "$new_repo" ]; then
    echo "$new_repo already exists"
    exit 1
fi

mkdir "$new_repo"
git init --bare "$new_repo" >/dev/null 2>&1\
    && echo "Initialized empty Git repository: git@$(uname -n):$1"
