#!/usr/bin/env bash

if [ $# -ne 3 ]; then
    echo "usage: setup-remote <name> <remote_name> <remote>"
    exit 1
fi

set -xe

USER="compromyse"

base_dir="$HOME"
repo="${base_dir}/$1"

case $repo in
    *\.git)
	;;
    *)
	repo="${new_repo}.git"
	;;
esac

if [ ! -d "$repo" ]; then
    echo "$repo does not exist"
    exit 1
fi

cd $repo
git remote add $2 $3
